[workspace]
resolver = "2"
members = [
    "contracts/intents-vault",
    "contracts/solver-registry",
    "contracts/mock-intents",
    "contracts/mock-ft",
    "contracts/limit-order-protocol",
    "contracts/cross-chain-escrow",
    "contracts/cross-chain-bridge",
]

[profile.release]
codegen-units = 1
# Tell `rustc` to optimize for small code size.
opt-level = "z"
lto = true
debug = false
panic = "abort"
# Opt into extra safety checks on arithmetic operations https://stackoverflow.com/a/64136471/249801
overflow-checks = true
